accounts:
  - name: alice
    coins: ["20000000000upact"]
  - name: bob
    coins: ["10000000000upact"]
validator:
  name: alice
  staked: "100000000upact"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "upact"
faucet:
  name: bob
  coins: ["1000000upact"]
